/**
 * Orchestration domain types.
 *
 * A plan is structured data, never free text: it is generated by a model and
 * therefore untrusted, so it must be validatable field by field before any
 * step runs.
 */

export type OrchestrationStatus =
  | "planning"
  | "running"
  | "synthesizing"
  | "completed"
  | "failed"
  | "cancelled";

export type StepStatus =
  | "queued"
  | "waiting"
  | "running"
  | "completed"
  | "failed"
  | "cancelled"
  | "timed-out";

/** One delegated unit of work. */
export interface OrchestrationStep {
  id: string;
  agentId: string;
  /** What the agent is being asked to do, in its own terms. */
  task: string;
  /** Step ids that must complete before this one may start. */
  dependsOn: string[];
  status: StepStatus;
  /** Run created for this step, once it starts. */
  runId?: string;
  /** The agent's own conversation for this delegation — never shared. */
  conversationId?: string;
  startedAt?: string;
  completedAt?: string;
  result?: AgentResult;
}

export interface OrchestrationPlan {
  id: string;
  /** Restatement of what the user asked for. */
  objective: string;
  steps: OrchestrationStep[];
  /**
   * True when Hermes judged the request simple enough to answer itself.
   * An empty plan is a valid outcome, not a failure.
   */
  direct: boolean;
}

/**
 * Structured outcome of one delegated run.
 *
 * Deliberately narrow: synthesis receives these rather than raw transcripts,
 * so the prompt stays bounded and Hermes cannot be fed an agent's entire
 * event history.
 */
export interface AgentResult {
  runId: string;
  agentId: string;
  stepId: string;
  status: "completed" | "failed" | "cancelled" | "timed-out";
  /** The agent's answer, or the reason it produced none. */
  summary: string;
  findings?: string[];
  /** Present when the step did not succeed. Never a provider internal. */
  failureReason?: string;
  durationMs?: number;
}

export interface Orchestration {
  id: string;
  /** Hermes's own conversation — where the user sees the summary. */
  conversationId: string;
  missionId?: string;
  objective: string;
  status: OrchestrationStatus;
  plan?: OrchestrationPlan;
  steps: OrchestrationStep[];
  startedAt: string;
  completedAt?: string;
  /**
   * Depth in the delegation tree. 0 is a user-initiated orchestration; a
   * delegated agent runs at depth 1 and, under the current limits, may not
   * delegate further.
   */
  depth: number;
}
